### PR TITLE
Add way to change file attributes

### PR DESCRIPTION
**Pull request by angelsl**
Took me a while. Sorry about that.

### CODE REVIEW

**Comment by angelsl** [comment]
Hold on, don't merge yet.

Need to not show the attribute functionality for virtual files.

Also, thoughts on the interface itself?

**Comment by angelsl** [comment]
Okay. It no longer shows options to change on virtual files (and directories).

It works on directories now too.

**Comment by d0k3** [comment]
Alright, interface looks okay. You seem to have broken something, though. Check long file / dirnames.

The other pull request I'll take.

**Comment by angelsl** [comment]
Alright, updated.

The menu is only for files now. Attributes are set on exit, and the user is asked to confirm the changes.

**Comment by d0k3** [comment]
Okay, I'm nitpicking here, but, two things...

1. (press arrow keys to change attributes) -> make this short, this line shouldn't be longer than the above block ([arrow symbols] to change attribute) would be enough (whereas [arrow symbols] are the actual arrow symbols).
2. The confirmation dialogue will look bad for actual long filenames - gotta change that. Tbh, to me, that dialogue seems like overkill anyways. It would be enough if the bottom line said (<A> to apply, <B> to cancel), maybe even only after a change is detected.

Anyways, look into that, and I'll take it over.

**Comment by d0k3** [comment]
Alright, I took it over locally, and added the two mentioned changes myself. I hope that's okay.

Normally I wouldn't push stuff that quick, but there are some bigger file reorganizations underway, so I wanted this pull request through before that happens.

**Pull request closed without merging**
