### PR TITLE
Fixed a bunch of typos in the README

### PR DESCRIPTION
**Pull request by DMSalesman**

### CODE REVIEW

**Comment by d0k3** [comment]
Taken over locally. One thing, though - before you do a pull request, make sure your local source is up to date with master. Otherwise I need to some git voodoo to not mess up the commit history.

**Comment by DMSalesman** [comment]
@d0k3 I used `git rebase` to update my local fork after fetching your latest source, and pushing back changes to remote. `git diff` said that there were no differences between our `master` branches. Is there anything more to do, in order to ensure that I have an exact clone?

**Comment by d0k3** [comment]
It's best you do you fresh clone of the repo, at least everytime after I merged in your changes.

**Comment by DMSalesman** [comment]
Will do, thanks.

**Pull request closed without merging**
