### PR TITLE
Update Cleanup SD Card and add Deleting Friendlist

### PR DESCRIPTION
**Pull request by Validusername16**

### CODE REVIEW

**Comment by d0k3** [comment]
I trust you tested this enough? I'll review this later.

**Comment by Ty-Dye** [comment]
I would love to see this in GM9!

**Comment by d0k3** [comment]
Okay, I thought about this for a bit, and you really should do that pull request to annson24's repo first:
https://github.com/annson24/GM9Megascript

@annson24 is the maintainer of the script, so I'll trust his judgement about these additions. I'll take them if @annson24 does.

**Comment by eip618** [comment]
@d0k3 this should probably be closed and the scripts pulled from annson's repo as they contain some changes not present here.

**Comment by d0k3** [comment]
Can @annson24 do the pull request? Or one of you guys. I could do it myself, but I think the commit ownership does not belong to me :).

**Comment by eip618** [comment]
to be honest, i have no idea how to PR a file from one repo to another which isnt a fork of the first.

**Comment by d0k3** [comment]
Just fork GM9, replace the Megascript, do a pull request. Can you do that?

**Comment by d0k3** [comment]
Alright, did it myself. Thank @Validusername16, @eip618 and @annson24!

**Comment by eip618** [comment]
sorry! i've been a little bit busy with... yknow, life over the past few days. sorry i didn't get the message.

**Pull request closed without merging**
