### PR TITLE
Finishing game installer functionality

### PR DESCRIPTION
**Pull request by d0k3**
This is a draft pull request, intended for testing and continued development (fixing bugs, adding missing feature) of the game image installing feature.

Here's a non-conclusive list of stuff still left to do:
* Identify and properly test all possible cases, fix any bug that comes up
* Implement cleanup on failed install (this needs uninstaller functionality first)
* Better handling for common issues (not enough space, title.db / import.db missing) with error messages
* Installer function for tickets(?)

Thanks go to @TurdPooCharger who has already started testing, looking forward to further bug reports.

### CODE REVIEW

**Comment by TurdPooCharger** [comment]
Copied and pasted from PM.

***

Alright, so after spending a better part of last night trying to fix my devkitarm setup, I finally got my computer to compile the GameInstaller fork. For some reason, my computer did not have [firmtool](https://github.com/TuxSH/firmtool) installed and updating devkitarm through pacman did not find this to be missing.


**Test Setup**
- Old 3DS XL (borrowed from cousin)
- 4 GB Toshiba SD card (FAT32 + 32 KB cluster size, H2testw passed)
- boot9strap v1.3 (both FIRM0/FIRM1)
- Sys 11.13.0-45U
- Luma3DS v10.1.3
- sdmc:/luma/payloads/
  * GodMode9_GameInstaller.firm (last commit: 70031d9)
  * GodMode9_v1.9.1.firm
- Homebrew Launcher v2.1.2
- All unused tickets were deleted. Only system tickets retained.
- etc.


**Initial Observations (Internal Notes)**

1. To install a CIA,
    - **[0:] SDCARD (NOLABEL)** → `example.cia` → **CIA image options...** → **Install game file**


2. GameInstaller requires the **Nintendo 3DS** folder to be present with these SD database file(s).
    - **sdmc:/Nintendo 3DS/**<****ID0****>**/**<****ID1****>**/dbs/**
      - ~~`import.db`~~
      - `title.db`

Not having the `title.db` will result in a '**Install fail**' message.
Not having the `import.db` will cause HOME Menu to not list installed titles.

***

## Test No.1 - Can GameInstaller install an SD title?
For this test, I booted the o3DSXL without the **Nintendo 3DS** folder on the SD card. Upon seeing HOME Menu, the 3DS firmware would create a new Nintendo 3DS folder with just the **extdata** subfolder. I visited **Nintendo 3DS Camera** → **Homebrew Launcher** →  **FBI** (3dsx) to create the missing (empty) `import.db` and `title.db`. CIAs are not installed at this point.

I boot to **GM9**_v1.9.1 and make a copy of the **Nintendo 3DS** folder named as **Nintendo 3DS (reference)**. In the **[1:] SYSNAND CTRNAND** directory, I also make a copy of the **dbs** folder and name this as **dbs_nand (reference)**.

Exiting **GM9**, I revisit **FBI** (3dsx) and install `FBI.cia` (v2.6.0 / 1.09 MB / 7DC5B2B1) to HOME Menu. Pressing the (HOME) button to go back to HOME Menu, the **FBI** (cia) gift icon is unwrapped but not launched. The icon and spinning cube banner are observed to be present.

I boot to GameInstaller and extract the decrypted contents of **FBI**'s **<TID_LOW>** subfolder. The title entry in the `title.db` and the ticket in `ticket.db` are also extracted.

1. **[A:] SYSNAND SD/title/00040000** → hold (R)-shoulder and press (A) on **0f800100** → **Copy to 0:/gm9/out**
2. **[A:]SYSNAND SD/dbs/**`title.db` → **Mount as DIFF image**
3. **[T:] BDRI IMAGE/**`000400000F800100` → **Copy to 0:/gm9/out**
4. **[1:] SYSNAND CTRNAND/dbs/**`ticket.db` → **Ticket.db options...** → **Mount image to drive**
5. **[T:] BDRI IMAGE/homebrew/**`000400000F800100.00000000.tik` → **Copy to 0:/gm9/out**

The **0f800100** , `000400000F800100` , and `000400000F800100.00000000.tik` are placed in a parent folder called **FBI (FBI installed)**.

The **Nintendo 3DS** folder is renamed to **Nintendo 3DS (FBI installed)**, and a copy of the **Nintendo 3DS (reference)** is pasted as a replacement **Nintendo 3DS** folder.

The six (6) .DB files within **dbs_nand (reference)** are copied and pasted into **1:/dbs** directory.

***

There was some difficulties replacing the folders and files where GameInstaller mentioned '**Out of memory.**' and would fail to recognize the replacement **Nintendo 3DS** folder. A quick press (START) and hold (START) reboot to GameInstaller was needed to continue the test.

***

I install the `FBI.cia` in GameInstaller and repeat the above five steps extracting those output files to a folder called **Nintendo 3DS (GM9 installed)** and **FBI (GM9 installed)**.

Exiting GameInstaller, booting to HOME Menu, and unwrapping **FBI**'s gift icon, the icon was observed to be black and the banner was missing. Launching the title results in this error.

> **An error occurred (ErrDisp)**
> Error type: card removed
> The card was removed.
> Press any button to reboot.

**Results**
Cross comparing the hashes between the two output folders,
- **FBI (FBI installed)**
- **FBI (GM9 installed)**

, there was a difference between the title entry and .CMD files.

Results_Test#1

I have no understanding of the title entry's data fields and the only comment I can add is that GameInstaller always writes block 0x50–52 block as '**GM9**'.

The `00000001.cmd` from GameInstaller appears to be creating the version meant for system titles without the CMACs. Here's a course refresher if needed.

- https://github.com/d0k3/GodMode9/issues/340#issuecomment-488637709

If I swap a copy of just the .CMD from **(FBI installed)** over to **(GM9 installed)**, that **Nintendo 3DS** (GM9 installed) folder will successfully launch **FBI** (cia).

Overlooking the NAND vs SD *.cmd bug and assuming the title entry's discrepancy are just placeholder values for testing purposes, I consider this CIA installation relatively successfully.

**NOTE**
As I report back my findings for more test, I will not repeat writing down the exact/similar procedures as detailed as this first test. This one was to establish or making clear the testing methodology and to help jump start overcoming my writer's block.

I will continue simple install tests for dsiware and system title next on this (70031d9) build before trying more complex arrangements or prodding hard for bugs (ie, pitfalls, stress limits) will come much later.

**Comment by TurdPooCharger** [comment]
## Test No.2 - Can GameInstaller install a CTRNAND title?
I chose **Health & Safety** as the test system title.

1. **GodMode9** (v1.9.1) → hold (R)-shoulder and press (A) on **[1:] SYSNAND CTRNAND** → **Search for titles**
   - `0004001000021300 Health and Safety Information (CTR-N-HACE) (U).legit.cia`
   - Renamed this file to `H&S.legit.cia`.

2. Copied these files and folders.
   - **1:/title/00040010** → hold (R)-shoulder and press (A) on **00021300** → **Copy to 0:/gm9/out**
   - **1:/dbs/**`ticket.db` → **T:/system** → `0004001000021300.00000000.tik` → **Copy to 0:/gm9/out**
   - **1:/dbs/**`title.db` →  **T:/** → `0004001000021300` → **Copy to 0:/gm9/out**
   - These items are placed in a folder called: **1 - original**

3. **FBI** (3dsx) → **Titles** → **Health and Safety Information** → **Delete Title And Ticket**
    **FBI** → **SD** → `H&S.legit.cia` → **Install CIA**

4. GameInstaller → Copied these files and folders.
   - 1:/title/00040010 → **00021300**
   - 1:/dbs/ticket.db → T:/system → `0004001000021300.00000000.tik`
   - 1:/dbs/title.db → T:/ → `0004001000021300`
   - These items are placed in a folder called: **2 - FBI**

5. **dbs_nand (reference)** → restore the six (6) .db files to **1:/dbs**
   - **1:/title/00040000** → press (X) to delete **00021300**
   - **1 - original** → press (Y) to **[CLIPBOARD]** select **00021300**
   - **1:/title/00040000** → press (Y) → **Copy path(s)** → etc.

6. Press (START) → HOME Menu → **Health & Safety** (verify the title launches)
7. **FBI** → **Titles** → **Health and Safety Information** → **Delete Title And Ticket**
8. GameInstaller → `H&S.legit.cia` → **CIA image options...** → **Install game file**

9. Repeat step 4, but put the items in a folder called: **3 - GM9**
10. Repeat step 6. GameInstaller installed H&S has the system title appear and launch.
11. Repeat step 5.

12. Repeat step 3, except no deleting **Health & Safety**.
    - **FBI** → **SD** → `H&S.legit.cia` → **Install CIA** 

13. Repeat step 4, but put the items in a folder called: **4 - FBI (no delete)**
14. Repeat step 5.
15. Repeat step 8, except **Health & Safety** not deleted beforehand.
16. Repeat step 9, but put the items in a folder called:  **5 - GM9 (no delete)**

**Results**

Results_#2


**BUG**
When installing a CIA, GameInstaller does not erase the **<TID_LOW>** folder. Anything that is currently installed will be either be overwritten, replaced, or left untouched. This can result in orphaned files (usually leftover .TMD files) that can later interfere with backing up CIAs or verifying intact installed titles (**TMD file options...** → **Verify file**).

**Comment by aspargas2** [comment]
Regarding the out of memory error, it's possible that there's a memory leak somewhere. I'll look into this when I get the chance.

Regarding the "GM9" string in the title info entry, that's fully intentional to mark a title info entry built my gm9. We have no idea what those 4 bytes are and their value doesn't seem to affect anything.

The bug with the .cmd files for SD titles should be fixed in commit 5f3ac47.

Regarding the old contents, tmd, and cmd not be overwritten, I agree that this needs to change. Unconditionally erasing the `content` folder for the title being installed if it exists should be fine.

**Comment by TurdPooCharger** [comment]
@aspargas2, what are the data fields in block 0x00–0F for the title entry? Is the total install size of that title (the reported blocks in **Data Management**) contained here?

Why does GameInstaller has the offset 0x0E set to the value **02** versus FBI having it as **00** ?

These I'm guessing are...
- **0x14–17:** contentID for the TMD(?)
- **0x18–1B:** contentID for the CMD(?)

For the random nature of block 0x50–53, I'll ignore this from now on. Maybe it relates to date and time when the title was installed?

***

I'll continue on **Test No.3 - Can GameInstaller install TWL title(s)?** with a compile of the latest `gameinstaller_next` fork.

**Comment by aspargas2** [comment]
The format of the title info entry is documented [here](https://3dbrew.org/wiki/Title_Database#Title_Info_Entry). Offset 0xC is the 4-byte title version. If I recall correctly, there was some issue related to generation of this field in the past, but I'll have to remind myself about the details of that. Thanks for pointing out that gameinstaller did this incorrectly; I had missed that.

You would be correct in your assumptions regarding the u32 fields at 0x14 and 0x18.

**Comment by aspargas2** [comment]
Also, I had meant to mention this earlier, but firmtool is a tool that isn't considered to be part of devkitARM, so dkp-pacman wont get it for you. GodMode9's readme lists it as a requirement seperately from devkitARM.

**Comment by TurdPooCharger** [comment]
## Test No.3 - Can GameInstaller install TWL system titles?
- This test follows the same procedures of Test No.2 but with the four (4) TWL system titles from the **[2:] SYSNAND TWLN**.
  - 00048005484E4441 - DS Download Play
  - 0004800542383841 - Nintendo DSi™ (DS INTERNET)
  - 0004800F484E4841 - Nintendo DS Cart Whitelist
  - 0004800F484E4C41 - TWL Version Data 
- The `gameinstaller_next` fork that was used was compiled with the last commit (ee061e4).
- The '**3 - GM9 (yes delete)**' case folder refers to deleting that title and its ticket in FBI before installing the CIA with GameInstaller. The leftover files bug found in Test No.2 hasn't been addressed in the compiled build.
- **unrelated bug:** Pulling up the keyboard when creating a new folder or renaming a file freezes GameInstaller.

**Results**

Result_#3

In the title entries, the Title Size (block 0x00–07) differs slightly between original and FBI/GM9. 

DS INTERNET
- original: 0x140B34 bytes (1313588 bytes ≈ 1.25 MB)
- FBI/GM9: 0x154000 bytes (1392640 bytes ≈ 1.32 MB)

I think the slight size differences boils down to how the titles were installed (ie: nand flashed at factory, eShop download, system update, cia).

That mystery block 0x50–53 is all zeros for 3 of the 4 TWL system titles. ¯\\_(ツ)_/¯

The original's title entry for **TWL Version Data** was the most baffling, having a Product Code (block 0x30–3F) with random(?) values and a Title Size of 0x4B34 bytes vs FBI/GM9's 0x18000 bytes.

As far as functionality goes, the GM9 installed DS Internet launches without a hitch.
- System Settings → Internet Settings → Nintendo DS Connections

***

## Test No.4 - Can GameInstaller (re-)install a legit DSiWare game?
This test was made possible because my cousin purchased this game from eShop.
- `000300044B513945 Zelda Four Swords (TWL-KQ9E) (DSi Exclusive) (U).legit.cia`

The title was dumped in GM9 v1.9.1 with the '**Use personalized ticket (legit)**' option. **CIA checker tool** verifies both the **Ticket/TMD** as _legit/legit_.

**Results**

hashes_#4

**FBI** was excluded from this test because it failed to install the legit dumped CIA with this error. I'm not sure if the error stems from FBI or that the CIA is a false legit.

FBI_0xDE0806A

While the GM9 installed game does launch, not having the SAV in place will cause in-game saving issues.

dsiware_no_sav

When installing a private legit CIA, GameInstaller strips out the ConsoleID data field in the ticket.

tickets_#4

Here's a quick refresher on the ticket structure.
- https://github.com/d0k3/GodMode9/pull/604#issuecomment-647986981

I think that editing measure is okay when installing the CIA on a different 3DS system than the one the CIA was sourced from. Maybe also strip out the eShop accountID (block 0x21C–21F) for extra safety.

When installing a private legit CIA back onto the source system, the legit ticket should be kept intact. Compare the ticket's ConsoleID against the **[M:] MEMORY VIRTUAL/**`otp_dec.mem` (block 0x04–08).

**Side Notes**
- Not all DSiWare titles have saves.
- The save file for DSiWare games are named either `public.sav` or `private.sav`.
- Unlike NATIVE and AGB games, DSiWare saves are not un-initialized where the first 0x20 bytes are zeros. They are FAT images.
- The `public.sav` for Zelda4Swords is FAT12.
- I can't recall if I saw some games with saves as FAT16 or if they're all FAT12. Will need to double check later.

**Comment by TurdPooCharger** [comment]
## Test No. 5 - Can GameInstaller install an SD game title straight from cartridge and its various derived .3DS & .CIA?
- The `gameinstaller_next` fork that was used for this test was the previous one from Tests No.3-4 with commit (ee061e4).
- I compiled a build with newer commit (85d83d7) but failed to switch over to this when changing from my 4 GB Toshiba to 32 GB Samsung SD card.
- This lapse in notice came too later after collecting all the raw data. Some of the findings presented here might not reflect bugs that are in the more current build.
- **minor bug:** GameInstaller will crash if the screens are closed when '**Install success**' is reached with the green blinking LED indicator.

This test puts GameInstaller to grueling rounds of installing the same game but in different formats. Alongside the o3DSXL, my cousin also lent his cart copy of **Pokémon Sun**. I would have preferred a smaller sized game; you work with what you got.

The exact game in question.
- [[DAT-o-MATIC] 1609 - Pokemon Sun (USA) (En,Ja,Fr,De,Es,It,Zh,Ko)](https://datomatic.no-intro.org/index.php?page=show_record&s=64&n=1609)

Because of the FAT32 storage size limit, here are the actual hashes when adjusting for the -1 byte.
- ENCRYPTED - 4.00 GB (0x100000000 bytes) - CRC32: 9B7AEABA
- ENCRYPTED - 3.99 GB ( 0xFFFFFFFF bytes) - CRC32: **11427A19**
- DECRYPTED - 4.00 GB (0x100000000 bytes) - CRC32: 5C4780E8
- DECRYPTED - 3.99 GB ( 0xFFFFFFFF bytes) - CRC32: **FB809C62**

***

Here comes the tricky part explaining what is what for each case.

1. **[C:] GAMECART (CTR<private_header>)/**`0004000000164800_v00.3ds` → **NCSD image options...** → **Install game file**

2. **[C:] GAMECART (CTR<private_header>)/**`0004000000164800_v00.trim.3ds` → **NCSD image options...** → **Install game file**

3. **C:/**`0004000000164800_v00.3ds` → **Copy to 0:/gm9/out** → ... → **Install game file**

4. **C:/**`0004000000164800_v00.trim.3ds` → **Copy to 0:/gm9/out** → ... → **Install game file**

5. Taking the `*_v00.3ds` from cases 1 or 3 → **NCSD image options...** → **Decrypt file (0:/gm9/out)** → ... → **Install game file**

6. Taking the `*_v00.trim.3ds` from cases 2 or 4 → **NCSD image options...** → **Decrypt file (0:/gm9/out)** → ... → **Install game file**

7/8/17/18. - Taking any `*.3ds` from cases 1–6 → **NCSD image options...** → **Build CIA from file** → Install output decrypted `*.cia` with program or app of choice.

9/10. - Taking the decrypted `*.cia` from cases [7/8/17/18] → **CIA image options...** → **Encrypt file (...)** → **Encrypt to 0:/gm9/out** → Install output re-encrypted `*.cia` with program or app of choice.

11/12. Taking the decrypted `*.3ds` from cases 5 or 6, convert this into a `*.cia` with [3dsconv](https://github.com/ihaveamac/3dsconv/releases). Install the output decrypted `*.cia` with program or app of choice.

13/14. Taking the encrypted `*.3ds` from cases 3 or 4, convert this into a `*.cia` with 3dsconv. Install the output encrypted `*.cia` with program or app of choice.

15/16. Taking the encrypted `*.3ds` from cases 3 or 4, decrypt this with [Batch CIA 3DS Decryptor](https://gbatemp.net/threads/batch-cia-3ds-decryptor-a-simple-batch-file-to-decrypt-cia-3ds.512385/). Convert the output `*-decrypted.3ds` into a `*.cia` with 3dsconv. Install the output decrypted `*.cia` with program or app of choice.

***

**Results**

Results_#5

- The hashes listed in each case column are the decrypted versions of the files. In GodMode9, this would normally be pulled out of the **[A:] SYSNAND SD**. For the sake of efficiency, I used **Duplicate Cleaner Pro** (by DigitalVolcano) to find files with the same hashes in encrypted form and then back searched the unique decrypted hash values with [ninfs](https://github.com/ihaveamac/ninfs) and [7-Zip](https://www.7-zip.org/download.html) (right mouse click on file → **CRC SHA**).

- Cases 17 & 18 were done last and almost as a last moment afterthought. They were included for reassurance on whether the outputs for (7) FBI and (8) GM9 could be trusted and to compared against something comparable using (17) DevMenu and (18) [custom-install](https://github.com/ihaveamac/custom-install/releases) as references. I placed these out of order next to 7 and 8 for easier examining.

- For cases 11–16, certain files such as the `*.tmd` and `*.tik` from the converted `*.3ds` → `*.cia` are not directly comparable by hash only due to different conversion conventions between GodMode9 vs 3dsconv. However, other files when grouped together as a set like the two `*.app` and `*.cmd` can be cross compared between cases.

- The re-encrypted `*.cia` (**D5642572**) for cases 9 and 10 is a bit weird. The encryption process reverted the manual (`0000001.app`) from (**47DB3F6B**) back to (**0C5A2919**) as one might expect. The game (`0000000.app`) on the other hand did not likewise return from (**89C4BFCF**) to (**EFCBA9CC**). Similar mismatch of expected vs actual hash was observed for the encrypted `.3ds` → decrypted `.cia` for cases 15 and 16. I did not find these discrepancies worth pursing for closer examination as they fall outside the purview of this PR.

- All sixteen cases produced `00000001.sav` in that size with the first 0x20 bytes un-initialized or filled with 00's.

- I launched both manual and game for cases [2/6/8/10/12/14/16]. For the game portion, I stopped short of the language selection screen. No dummy profile saves were made. I considered a case to be successful (function-wise) if the extdata subfolder was produced upon returning to GodMode9 for check-up. Each case produced the **A:/extdata/00000000/00001648**. :+1: 

***

**BUGS**

title_entries_#5

- [[3dbrew.org] Title Database](https://3dbrew.org/wiki/Title_Database#Title_Info_Entry)

We already touched base about the differences in **Title Version** (block 0xC–F). Because I did this test on an older build, (@aspargas2) you might have already fixed this. For GameInstaller, the title entry's Title Version is not consistent depending whether the source rom was `*.3ds` and `*.cia`. When installing the same `*.cia`, that inconsistency extends between FBI/DevMenu vs GameInstaller and custom-install. Calling @ihaveamac for tag along if this something to look into.

The **ExtdataID_LOW** (block 0x20-23) is missing. I took a brief look in the custom-install's source code. This appears to be pulled from the game's `00000000.app` → `extheader.bin` at block 0x230–233.

tickets_#5

- [[3dbrew.org] Ticket](https://www.3dbrew.org/wiki/Ticket#Ticket_Data)

I understand there isn't a formal standard in how to go about producing fake or nonlegit tickets. For GameInstaller, the trailing end of the ticket in block 0x2F0–34F when installing `*.3ds` is different than installing `*.cia`. I chalk this up to holdover source code from the original Cart Installer fork.

I'm guessing the difference in **Ticket Title Version** (block 0x1E6–1E7) in tickets probably relates to the Title Version found in the title entries.

TMD_#5

- [[3dbrew.org] Title metadata](https://www.3dbrew.org/wiki/Title_metadata#Header)

Ditto for **Title Version** (block 0x1DC–1DD) for the `*.tmd`.

**Comment by ihaveamac** [comment]
The title version block at 0xc should be more like 2 fields, title version (from tmd) and NCCH version ([offset 0x112](https://www.3dbrew.org/wiki/NCCH#NCCH_Header)). This is apparently needed to fix DLP child contents (maybe manual too but I haven't looked into it). I don't know why installing through the OS doesn't set this field though, unless the version is actually 0 or it doesn't do this for titles without extra contents.

**Comment by ihaveamac** [comment]
Seems like the NCCH version field is empty if the title has no DLP child, but title version is always set. Observed in Mario Kart 7 (0004000000030800) and Tri Force Heroes (00040000001b5000) which have an NCCH version set and have a DLP child, and Pokémon Ultra Sun (00040000001b5000) and Update for Mario Kart 7 (0004000e00030800) which have an NCCH version set to 0 and no DLP child. All 4 titles have NCCH version = 2 in the main content.
[tie.zip](https://github.com/d0k3/GodMode9/files/5072239/tie.zip)

**Comment by d0k3** [comment]
Okay, as you see, I worked quite a bit on this. Just a few remarks:
* I can explain the differences in original 00000000.app from the cart dump vs 00000000.app inside a CIA or installed. As you know, carts are not really intended for installing. To make them work we need to change a small thing in the extended header. Of course we don't revert that change, as we can't really tell if the CIA was build from a cart dump or digital content afterwards.
* The differences in the tickets are acceptable, they still need some looking into. Maybe @aspargas2 can help (https://user-images.githubusercontent.com/35666439/90171611-be2dc380-dd6f-11ea-9761-7da47016fc2a.png)
* The NDS save file pita will need a little more time. We will manage, of course.
* I'm not 100% sure if all my fixes work as they should in all cases. Further testing may be required, but a reduced setup is more than acceptable of course.

To be honest, I somehow lost track and I don't know if I didn't miss anything. If you can, can you provide us with a list of issues that we haven't adressed? Or issues with an unknown state (adressed, but fix untested)? I will be able to do quite a lot next week, hoping to improve this a lot.

Anyways, thanks a lot, @TurdPooCharger! Bug reports such as this, and really thorough testing is highly appreciated and helps us make features such as this possible.

Also, thanks, @ihaveamac - you also know without all your research we would never have gotten this far.

**Comment by TurdPooCharger** [comment]
dsiware_tmd_saves_info

- [[3dbrew.org] Title metadata](https://www.3dbrew.org/wiki/Title_metadata#Header)

The above example `*.tmd` is a fictitious title. There are a handful I've seen that have two saves. While I haven't come across a real DSiWare game that has all three saves, I think having any save type is independent of each other. 

**Example 1** - This game has both `public.sav` and `private.sav`.
000480044B344B56
Trailblaze™: Puzzle Incinerator
TWL-N-K4KV

**Example 2** - This game has both `public.sav` and `banner.sav`.
000480044B4E4445
Brain Age™ Express: Arts & Letters
TWL-N-KNDE

***

This should help in your programming when creating FAT12 images for the `public.sav` and `private.sav`. Use these as reference for comparison. Just know that the examples provided in the archive does not encompass all the possible save sizes. 

- [dsiware_save_sizes.7z](https://drive.google.com/file/d/1wWkttyFQtnL6F69aGK191lInfliz4YJd/view)

Test installing those titles with `banner.sav` on both FBI and DevMenu, they all appears to be 0x4000 bytes filled with randomly generated values.

**Comment by d0k3** [comment]
Thanks a ton, @TurdPooCharger! That info, and especially the archive with those savegames will help me a lot. To be honest, I was already searching for something like this.

**Comment by d0k3** [comment]
Alright, I had to rebase this on master because of a very important fix done by @Wolfvak (renaming functions should work again now). Everyone working with this will have to clone fresh. Sorry about the trouble, everyone!

**Comment by d0k3** [comment]
@TurdPooCharger - just a quick one. The SRL flag and `banner.sav` was a good find. There's more info on what the SRL flag actually means on [GBATEK](https://problemkaputt.de/gbatek.htm). 1 means "requires EULA". I guess I'll just have to take that over from somewhere in the TWL header.

**Comment by d0k3** [comment]
Merged to master and closed, continued in #621

**Pull request closed without merging**
