### PR TITLE
Update user manual

### PR DESCRIPTION
**Pull request by DMSalesman**

### CODE REVIEW

**Comment by Wolfvak** [comment]
honestly, wouldn't it be easier to just merge the script used to do this instead of having to ask you each time there's a release with an updated readme?

**Comment by DMSalesman** [comment]
Sure, but I'm in no way proficient enough with `make` to risk submitting a pull request, at the moment.

**Comment by Wolfvak** [comment]
if you use a python script just merge that into the utils dir and I'll add it to the makefile

**Comment by d0k3** [comment]
Merged, thank you!

**Comment by DMSalesman** [comment]
@Wolfvak The Python script is what does the job, but there's also a "patch database" consisting of a `gzip`ped .json, which takes care of the more advanced search and replaces. Is there a way to handle that?

**Comment by Wolfvak** [comment]
I suppose it could be placed in the same dir as the script?

**Comment by DMSalesman** [comment]
@Wolfvak #546.

**Pull request closed without merging**
