### PR TITLE
Add Translations

### PR DESCRIPTION
**Pull request by Epicpkmn11**
- Depends on #768, merge that first
   - I'm opening this as a second PR for clarity, that has all the code this has all the non-code
- Current translations, in order of completeness: Japanese, Indonesian, German, French, Spanish, Japanese (kana only), Dutch, Ryukyuan (Uchinaaguchi), Italian, Russian, Polish
   - Only Japanese and Indonesian are 100% complete so far, I've left out the really incomplete ones (tbh Ryukuan onwards or maybe even Spanish on probably aren't worth using atm, but I hope that by seeing the language people are more likely to want to translate)
   - Perhaps translation updates can be hotfixed in or Universal-Updater can download them from elsewhere
   - I'd recommend waiting to merge this until shortly before the release and let me know beforehand and I can check if more translations have been done
   - @/Translators if you want to get your translations in now's the time to do it
- Expands the default font slightly for better Cyrillic/Greek/Extended Latin support and `日本語琉球諸中文简体繁體한국어` which should cover the names of all CJK languages
- Adds a separate font for Japanese with Kanji
   - This is identical to the base font just larger so it could simply replace it, however the base font is 10 KB and this is 86 KB so not sure you'd want that in the binary, SD space is cheap and it can be skipped
   - LZSS compression could get it down as low as 55 KB, if you want I can implement LZSS to the FRF format (just compress the CDAT and CMAP blocks, add some revision marker so it doesn't load on older versions) but I'm not sure it's worth the effort cause that's still quite large and it's already distributed in a zip

### CODE REVIEW

**Comment by d0k3** [comment]
@Epicpkmn11 - we already missed this years anniversary date, so there's no need to rush. I do want to release all that new stuff, though, of course, and there will be a (although belated) anniversary release.

Any estimate on how "finished" those translations are at the current time?

**Comment by Epicpkmn11** [comment]
Crowdin shows the percentages:

スクリーンショット 0005-04-15 10 25 57

Japanese done, German and French pretty good, Dutch, Spanish, Russian, Polish sorta usable

**Comment by ItzSwirlz** [comment]
> Spanish, Russian, Polish sorta usable

It helps me learn Spanish so I'm happy :)


please pull this branch

**Review by ItzSwirlz — APPROVED** [review]

**Comment by d0k3** [comment]
@ItzSwirlz - don't worry, it will be megred. @Epicpkmn11 , how about this: I can wait with the next release until you say the translations are finished as far as they need to be. A rough estimate on the time frame would be nice.

**Comment by d0k3** [comment]
Should have done this long ago, merged. Thank you @Epicpkmn11 !

**Comment by Minionguyjpro** [comment]
> I'd say it's fine now, activity has been slow on Crowdin apart from Indonesian being translated so I don't expect many major changes soon. More translations will trickle in over time, but if you wait for everything to be complete you'll likely be waiting a very long time... Currently there's 2 (ja, id) complete translations, 2 (de, fr) pretty good, and 5 that are at least somewhat worthwhile.
> 
> It wouldn't surprise me if a lot more people suddenly translate after the release (since that'll get people to actually know about it), so might be worth just hotfixing the zip after a bit or I could set Universal-Updater to download a separate up to date language zip from somewhere.

I will continue translating Dutch as person from The Netherlands soon.

**Comment by Minionguyjpro** [comment]
Looks pretty good now:
afbeelding

**Pull request merged**
