### PR TITLE
Emre009 patch 2

### PR DESCRIPTION
**Pull request by emre009**
https://github.com/emre009/GodMode9/commit/16b9ec17696a9e4c23779b63fa17abaa2415ea55
https://github.com/emre009/GodMode9/commit/054f0a8e91d262475998e7c1c334e17782ad4345

### CODE REVIEW

**Comment by ahoischen** [comment]
Please stop trying to merge your custom buttons. If you can't compile a build yourself, please ask someone more knowledgeable. These Pull Requests won't achieve anything.

**Comment by emre009** [comment]
I did it all to see if it was in Travis. Then I would have to remove them. Just show me how someone was released. Sorry I did not make any changes to the database. My only goal was to use the home menu.

**Comment by ahoischen** [comment]
You can always enable TravisCI for your forks by going to www.travis-ci.org and signing in with your GitHub account. I'm not familiar with Godmode9's build system, but it might be enough to just create a release on GitHub and wait for Travis to upload the file. Otherwise, you will have to compile it yourself. The instructions for that are in the .travis.yml file.

**Comment by d0k3** [comment]
Oh well... for Travis, the pull request would not have been required. If you really can't compile on your own right now, ask someone else. I will also make compiling a bit easier by removing submodules (today or tomorrow).

**Pull request closed without merging**
