### PR TITLE
added essential.exefs dump to the boot9&11 script

### PR DESCRIPTION
**Pull request by GlaZedBelmont**

### CODE REVIEW

**Comment by d0k3** [comment]
That's not so good, actually. If essential.exefs is not present, this prevents you from dumping the bootroms. Maybe dumping essential.exefs via another menu entry would be better? I'd also like to read @annson24 's take on this.

**Comment by d0k3** [comment]
@GlaZedBelmont - I can't take that pull request without the changes I requested. Want to still do them?

**Comment by GlaZedBelmont** [comment]
yeah, hold up, ill do the changes real quick.

something like if it doesnt find essential.exefs, it asks you if you still want to dump the bootroms

**Comment by d0k3** [comment]
Okay, sorry to have kept you waiting that long!

It would still be better to have a separate entry for dumping essential.exefs. Can you do that?

Normal course of action would be to first do a pull request on @annson24's repo.
https://github.com/annson24/GM9Megascript
Dunno if @annson24 (pingpingping) is still active, so it's okay to do pull requests here, too.

**Comment by d0k3** [comment]
Okay, I had a look over your changes and also tested the script. Your changes introduced some display errors ( strings too long) and, well, it should have been a separate entry all along. I tried to separate your changes into a new menu entry myself, but failed.

As we're nearing a new release and I actually want that feature in, I went ahead and added the menu entry and code myself. I still want to thank you for your contribution, we just couldn't merge it this time.

**Comment by GlaZedBelmont** [comment]
No problem, I PRed the script itself instead of PRing GM9

**Comment by GlaZedBelmont** [comment]
also, if you could add me and win9x to the script's credits, we both worked on the idea and creation of the script :smiley:

**Pull request closed without merging**
