### PR TITLE
Delete script preview fauture

### PR DESCRIPTION
**Pull request by windows-server-2003**

### CODE REVIEW

**Comment by windows-server-2003** [comment]
Oh , I made a mistake. I wanted to made pull request on my repository.I didn't want to make pull request to the original(this) repository.
Script preview future is very nice, but it made executing scripts slow.so I want to be able to choose Preview future/Executing speed.

**Comment by windows-server-2003** [comment]
I had to just commit.
Sorry for troubling you.I'm not familiar with Github, so I'll be more careful.

**Comment by d0k3** [comment]
Instead of doing this, why not open up an issue and upload a sample script?

**Comment by windows-server-2003** [comment]
I'm thinking about that, but released binaries will never be changed (even have broken FAT future). So I released without script preview future.

**Pull request closed without merging**
